/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    formations: Formation;
    formations_personnalisees: FormationsPersonnalisee;
    'structures-juridiques': StructuresJuridique;
    apprenants: Apprenant;
    articles: Article;
    categories: Category;
    tags: Tag;
    programmes: Programme;
    'rendez-vous': RendezVous;
    contacts: Contact;
    media: Media;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    formations: FormationsSelect<false> | FormationsSelect<true>;
    formations_personnalisees: FormationsPersonnaliseesSelect<false> | FormationsPersonnaliseesSelect<true>;
    'structures-juridiques': StructuresJuridiquesSelect<false> | StructuresJuridiquesSelect<true>;
    apprenants: ApprenantsSelect<false> | ApprenantsSelect<true>;
    articles: ArticlesSelect<false> | ArticlesSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    programmes: ProgrammesSelect<false> | ProgrammesSelect<true>;
    'rendez-vous': RendezVousSelect<false> | RendezVousSelect<true>;
    contacts: ContactsSelect<false> | ContactsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  globals: {};
  globalsSelect: {};
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  firstName?: string | null;
  lastName?: string | null;
  role: 'superAdmin' | 'admin' | 'formateur' | 'gestionnaire' | 'apprenant';
  status: 'active' | 'inactive' | 'suspended' | 'pending';
  phone?: string | null;
  address?: string | null;
  dateOfBirth?: string | null;
  avatar?: (string | null) | Media;
  permissions?:
    | {
        permission?:
          | (
              | 'users:read'
              | 'users:create'
              | 'users:update'
              | 'users:delete'
              | 'formations:read'
              | 'formations:create'
              | 'formations:update'
              | 'formations:delete'
              | 'apprenants:read'
              | 'apprenants:create'
              | 'apprenants:update'
              | 'apprenants:delete'
              | 'rendez_vous:read'
              | 'rendez_vous:create'
              | 'rendez_vous:update'
              | 'rendez_vous:delete'
              | 'documents:read'
              | 'documents:create'
              | 'documents:update'
              | 'documents:delete'
              | 'admin:access'
              | 'system:settings'
              | 'reports:access'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  lastLoginAt?: string | null;
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formations".
 */
export interface Formation {
  id: string;
  titre: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  duree: number;
  niveau: 'Débutant' | 'Intermédiaire' | 'Avancé';
  modalites: 'Présentiel' | 'Distanciel' | 'Hybride';
  prix: number;
  competences?:
    | {
        competence: string;
        id?: string | null;
      }[]
    | null;
  codeFormation?: string | null;
  image?: (string | null) | Media;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formations_personnalisees".
 */
export interface FormationsPersonnalisee {
  id: string;
  title: string;
  /**
   * Code unique de la formation (ex: A123456-DUPONT)
   */
  codeFormation: string;
  objectifs?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  programmeDetail?:
    | {
        jour?: string | null;
        duree?: string | null;
        modules?:
          | {
              titre: string;
              description?: string | null;
              duree?: string | null;
              contenu?: {
                root: {
                  type: string;
                  children: {
                    type: any;
                    version: number;
                    [k: string]: unknown;
                  }[];
                  direction: ('ltr' | 'rtl') | null;
                  format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                  indent: number;
                  version: number;
                };
                [k: string]: unknown;
              } | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  modalitesAcces?: {
    prerequis?: string | null;
    publicConcerne?: string | null;
    duree?: string | null;
    horaires?: string | null;
    delaisMiseEnPlace?: string | null;
    tarif?: number | null;
    modalitesReglement?: string | null;
  };
  contactFormateur: {
    nom: string;
    email: string;
    telephone?: string | null;
    role?: string | null;
    biographie?: string | null;
  };
  modalitesPedagogiques?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  ressourcesDispo?:
    | {
        ressource: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  modalitesEvaluation?: {
    typesEvaluation?:
      | {
          type: string;
          description?: string | null;
          id?: string | null;
        }[]
      | null;
    plateformeEvaluation?: string | null;
    grilleAnalyse?: string | null;
  };
  sanctionFormation?: string | null;
  niveauCertification?: string | null;
  accessibiliteHandicap?: {
    referentHandicap?: string | null;
    contactReferent?: string | null;
    adaptationsProposees?: string | null;
  };
  cessationAbandon?: {
    conditionsRenonciation?: string | null;
    facturationAbandon?: string | null;
  };
  statut?: ('EN_COURS' | 'FINALISEE' | 'LIVREE' | 'ARCHIVE') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "structures-juridiques".
 */
export interface StructuresJuridique {
  id: string;
  /**
   * Raison sociale de l'entreprise
   */
  nom: string;
  /**
   * Numéro SIRET à 14 chiffres
   */
  siret: string;
  /**
   * Code d'activité principale (ex: 6201Z)
   */
  codeApe?: string | null;
  adresse?: string | null;
  codePostal?: string | null;
  ville?: string | null;
  telephone?: string | null;
  email?: string | null;
  contactPrincipal?: {
    nom?: string | null;
    prenom?: string | null;
    fonction?: string | null;
    email?: string | null;
    telephone?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apprenants".
 */
export interface Apprenant {
  id: string;
  nom: string;
  prenom: string;
  email: string;
  telephone?: string | null;
  dateNaissance?: string | null;
  /**
   * 15 chiffres (ex: 1 85 03 75 120 123 45)
   */
  numeroSecuriteSociale?: string | null;
  /**
   * Pour les travailleurs indépendants
   */
  numeroCotisantIndividuel?: string | null;
  /**
   * Entreprise ou structure rattachée à l'apprenant
   */
  structureJuridique?: (string | null) | StructuresJuridique;
  /**
   * Programme auquel l'apprenant est inscrit
   */
  programme?: string | null;
  statut: 'prospect' | 'inscrit' | 'en-formation' | 'termine' | 'abandonne';
  /**
   * Pourcentage de complétion du parcours
   */
  progression?: number | null;
  /**
   * Remarques ou informations complémentaires
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles".
 */
export interface Article {
  id: string;
  titre: string;
  slug: string;
  contenu: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  resume: string;
  auteur: string;
  datePublication: string;
  statut: 'brouillon' | 'publie' | 'archive';
  categories?: (string | Category)[] | null;
  tags?: (string | Tag)[] | null;
  imagePrincipale?: (string | null) | Media;
  images?:
    | {
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  metaDescription: string;
  metaKeywords?:
    | {
        keyword?: string | null;
        id?: string | null;
      }[]
    | null;
  vue?: number | null;
  tempsLecture?: number | null;
  featured?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  nom: string;
  slug: string;
  description?: string | null;
  couleur?: string | null;
  icone?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  nom: string;
  slug: string;
  couleur?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes".
 */
export interface Programme {
  id: string;
  codeFormation: string;
  titre: string;
  description: string;
  duree: number;
  niveau: 'DEBUTANT' | 'INTERMEDIAIRE' | 'AVANCE';
  modalites: 'PRESENTIEL' | 'DISTANCIEL' | 'HYBRIDE';
  prix: number;
  competences?:
    | {
        competence: string;
        id?: string | null;
      }[]
    | null;
  objectifs?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  prerequis?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  programme?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  modalitesPedagogiques?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  evaluation?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  certification?: string | null;
  eligibleCPF?: boolean | null;
  codeCPF?: string | null;
  statut: 'actif' | 'inactif' | 'en_developpement';
  image?: (string | null) | Media;
  rating?: number | null;
  students?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rendez-vous".
 */
export interface RendezVous {
  id: string;
  programme: string | Programme;
  client: {
    nom: string;
    prenom: string;
    email: string;
    telephone: string;
    entreprise?: string | null;
  };
  type: 'positionnement' | 'information' | 'inscription' | 'suivi';
  statut: 'enAttente' | 'confirme' | 'termine' | 'annule' | 'reporte';
  date: string;
  heure: string;
  duree: number;
  lieu: 'visio' | 'presentiel' | 'telephone';
  adresse?: string | null;
  lienVisio?: string | null;
  notes?: string | null;
  rappelEnvoye?: boolean | null;
  createdBy: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts".
 */
export interface Contact {
  id: string;
  nom: string;
  email: string;
  telephone?: string | null;
  type: 'question' | 'reclamation' | 'formation' | 'devis';
  sujet: string;
  message: string;
  statut: 'nouveau' | 'enCours' | 'traite' | 'ferme';
  priorite: 'basse' | 'normale' | 'haute' | 'urgente';
  reponse?: string | null;
  dateReponse?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'formations';
        value: string | Formation;
      } | null)
    | ({
        relationTo: 'formations_personnalisees';
        value: string | FormationsPersonnalisee;
      } | null)
    | ({
        relationTo: 'structures-juridiques';
        value: string | StructuresJuridique;
      } | null)
    | ({
        relationTo: 'apprenants';
        value: string | Apprenant;
      } | null)
    | ({
        relationTo: 'articles';
        value: string | Article;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'programmes';
        value: string | Programme;
      } | null)
    | ({
        relationTo: 'rendez-vous';
        value: string | RendezVous;
      } | null)
    | ({
        relationTo: 'contacts';
        value: string | Contact;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'payload-kv';
        value: string | PayloadKv;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  firstName?: T;
  lastName?: T;
  role?: T;
  status?: T;
  phone?: T;
  address?: T;
  dateOfBirth?: T;
  avatar?: T;
  permissions?:
    | T
    | {
        permission?: T;
        id?: T;
      };
  lastLoginAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formations_select".
 */
export interface FormationsSelect<T extends boolean = true> {
  titre?: T;
  description?: T;
  duree?: T;
  niveau?: T;
  modalites?: T;
  prix?: T;
  competences?:
    | T
    | {
        competence?: T;
        id?: T;
      };
  codeFormation?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "formations_personnalisees_select".
 */
export interface FormationsPersonnaliseesSelect<T extends boolean = true> {
  title?: T;
  codeFormation?: T;
  objectifs?: T;
  programmeDetail?:
    | T
    | {
        jour?: T;
        duree?: T;
        modules?:
          | T
          | {
              titre?: T;
              description?: T;
              duree?: T;
              contenu?: T;
              id?: T;
            };
        id?: T;
      };
  modalitesAcces?:
    | T
    | {
        prerequis?: T;
        publicConcerne?: T;
        duree?: T;
        horaires?: T;
        delaisMiseEnPlace?: T;
        tarif?: T;
        modalitesReglement?: T;
      };
  contactFormateur?:
    | T
    | {
        nom?: T;
        email?: T;
        telephone?: T;
        role?: T;
        biographie?: T;
      };
  modalitesPedagogiques?: T;
  ressourcesDispo?:
    | T
    | {
        ressource?: T;
        description?: T;
        id?: T;
      };
  modalitesEvaluation?:
    | T
    | {
        typesEvaluation?:
          | T
          | {
              type?: T;
              description?: T;
              id?: T;
            };
        plateformeEvaluation?: T;
        grilleAnalyse?: T;
      };
  sanctionFormation?: T;
  niveauCertification?: T;
  accessibiliteHandicap?:
    | T
    | {
        referentHandicap?: T;
        contactReferent?: T;
        adaptationsProposees?: T;
      };
  cessationAbandon?:
    | T
    | {
        conditionsRenonciation?: T;
        facturationAbandon?: T;
      };
  statut?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "structures-juridiques_select".
 */
export interface StructuresJuridiquesSelect<T extends boolean = true> {
  nom?: T;
  siret?: T;
  codeApe?: T;
  adresse?: T;
  codePostal?: T;
  ville?: T;
  telephone?: T;
  email?: T;
  contactPrincipal?:
    | T
    | {
        nom?: T;
        prenom?: T;
        fonction?: T;
        email?: T;
        telephone?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "apprenants_select".
 */
export interface ApprenantsSelect<T extends boolean = true> {
  nom?: T;
  prenom?: T;
  email?: T;
  telephone?: T;
  dateNaissance?: T;
  numeroSecuriteSociale?: T;
  numeroCotisantIndividuel?: T;
  structureJuridique?: T;
  programme?: T;
  statut?: T;
  progression?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "articles_select".
 */
export interface ArticlesSelect<T extends boolean = true> {
  titre?: T;
  slug?: T;
  contenu?: T;
  resume?: T;
  auteur?: T;
  datePublication?: T;
  statut?: T;
  categories?: T;
  tags?: T;
  imagePrincipale?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  metaDescription?: T;
  metaKeywords?:
    | T
    | {
        keyword?: T;
        id?: T;
      };
  vue?: T;
  tempsLecture?: T;
  featured?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  nom?: T;
  slug?: T;
  description?: T;
  couleur?: T;
  icone?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  nom?: T;
  slug?: T;
  couleur?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "programmes_select".
 */
export interface ProgrammesSelect<T extends boolean = true> {
  codeFormation?: T;
  titre?: T;
  description?: T;
  duree?: T;
  niveau?: T;
  modalites?: T;
  prix?: T;
  competences?:
    | T
    | {
        competence?: T;
        id?: T;
      };
  objectifs?: T;
  prerequis?: T;
  programme?: T;
  modalitesPedagogiques?: T;
  evaluation?: T;
  certification?: T;
  eligibleCPF?: T;
  codeCPF?: T;
  statut?: T;
  image?: T;
  rating?: T;
  students?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rendez-vous_select".
 */
export interface RendezVousSelect<T extends boolean = true> {
  programme?: T;
  client?:
    | T
    | {
        nom?: T;
        prenom?: T;
        email?: T;
        telephone?: T;
        entreprise?: T;
      };
  type?: T;
  statut?: T;
  date?: T;
  heure?: T;
  duree?: T;
  lieu?: T;
  adresse?: T;
  lienVisio?: T;
  notes?: T;
  rappelEnvoye?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts_select".
 */
export interface ContactsSelect<T extends boolean = true> {
  nom?: T;
  email?: T;
  telephone?: T;
  type?: T;
  sujet?: T;
  message?: T;
  statut?: T;
  priorite?: T;
  reponse?: T;
  dateReponse?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}